include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude: [lib/**.config.dart, lib/**.g.dart, lib/**.freezed.dart]
  errors:
    invalid_annotation_target: ignore
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false