targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        options:
          auto_register: true
          class_name_pattern: ".*RepositoryImpl|.*DataSourceImpl|.*Bloc|.*Cubit|.*UseCase|.*UseCaseImpl|.*Service|.*ServiceImpl"
          file_name_pattern: "_impl|_bloc|_cubit|_usecase|_service"
        enabled: true
      injectable_generator:injectable_config_builder:
        options:
          auto_register: true
        enabled: true
