name: recipe_book
description: "A recipe book app"

publish_to: 'none'

version: 0.5.7+18

environment:
  sdk: ^3.9.0

dependencies:
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  font_awesome_flutter: ^10.10.0
  freezed_annotation: ^2.4.1
  get_it: ^8.2.0
  google_fonts: ^6.3.0
  injectable: ^2.4.1
  json_annotation: ^4.9.0
  objectbox: ^4.3.0
  objectbox_flutter_libs: ^4.3.0
  path: ^1.9.1
  path_provider: ^2.1.4

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.10
  commitlint_cli: ^0.8.1
  commitlint_config: ^0.1.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  husky: ^0.1.7
  injectable_generator: ^2.4.1
  json_serializable: ^6.9.2
  mockito: ^5.4.4
  objectbox_generator: ^4.3.0
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
