name: recipe_book
description: "A recipe book app"

publish_to: 'none'

version: 0.0.2+2

environment:
  sdk: ^3.9.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  commitlint_cli: ^0.8.1
  commitlint_config: ^0.1.2
  husky: ^0.1.7

flutter:
  uses-material-design: true
