name: recipe_book
description: "A recipe book app"

publish_to: 'none'

version: 0.0.2+2

environment:
  sdk: ^3.9.0

dependencies:
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  json_annotation: ^4.9.0


dev_dependencies:
  build_runner: ^2.4.10
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  commitlint_cli: ^0.8.1
  commitlint_config: ^0.1.2
  husky: ^0.1.7
  json_serializable: ^6.9.2
  very_good_analysis: ^9.0.0


flutter:
  uses-material-design: true
