// Mocks generated by Mockito 5.4.6 from annotations
// in recipe_book/test/unit/features/favorites/domain/usecases/get_favorite_meals_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:recipe_book/features/favorites/domain/repositories/favorite_repository.dart'
    as _i2;
import 'package:recipe_book/features/meals/domain/entities/meal.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FavoriteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoriteRepository extends _i1.Mock
    implements _i2.FavoriteRepository {
  MockFavoriteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> toggleFavorite(String? mealId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [mealId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Meal>> getFavoriteMeals() =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteMeals, []),
            returnValue: _i3.Future<List<_i4.Meal>>.value(<_i4.Meal>[]),
          )
          as _i3.Future<List<_i4.Meal>>);

  @override
  _i3.Future<bool> isFavorite(String? mealId) =>
      (super.noSuchMethod(
            Invocation.method(#isFavorite, [mealId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
