// Mocks generated by Mockito 5.4.6 from annotations
// in recipe_book/test/unit/features/favorites/data/repositories_impl/favorite_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:recipe_book/features/favorites/data/datasources/favorite_local_datasource.dart'
    as _i2;
import 'package:recipe_book/features/meals/data/models/meal_model.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FavoriteLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoriteLocalDataSource extends _i1.Mock
    implements _i2.FavoriteLocalDataSource {
  MockFavoriteLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> toggleFavorite(String? mealId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [mealId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isFavorite(String? mealId) =>
      (super.noSuchMethod(
            Invocation.method(#isFavorite, [mealId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<_i4.MealModel>> getFavoriteMeals() =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteMeals, []),
            returnValue: _i3.Future<List<_i4.MealModel>>.value(
              <_i4.MealModel>[],
            ),
          )
          as _i3.Future<List<_i4.MealModel>>);
}
