// Mocks generated by Mockito 5.4.6 from annotations
// in recipe_book/test/unit/features/meals/data/repositories_imp/meal_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:recipe_book/features/meals/data/datasources/meal_remote_datasource.dart'
    as _i2;
import 'package:recipe_book/features/meals/data/models/meal_model.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MealRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMealRemoteDataSource extends _i1.Mock
    implements _i2.MealRemoteDataSource {
  MockMealRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.MealModel>> fetchByLetter(String? letter) =>
      (super.noSuchMethod(
            Invocation.method(#fetchByLetter, [letter]),
            returnValue: _i3.Future<List<_i4.MealModel>>.value(
              <_i4.MealModel>[],
            ),
          )
          as _i3.Future<List<_i4.MealModel>>);
}
